services:
  # Production Database
  - type: pserv
    name: spend-smart-db-prod
    env: node
    plan: starter
    databaseName: spendsmartprod
    databaseUser: spendsmartproduser
    region: oregon

  # Staging Database
  - type: pserv
    name: spend-smart-db-staging
    env: node
    plan: starter
    databaseName: spendsmartstaging
    databaseUser: spendsmartstaginguser
    region: oregon

  # Production Backend
  - type: web
    name: spend-smart-backend-prod
    env: node
    plan: starter
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: spend-smart-db-prod
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://spend-smart-frontend-prod.onrender.com
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: /api
    autoDeploy: true
    branch: main
    rootDir: apps/backend

  # Staging Backend
  - type: web
    name: spend-smart-backend-staging
    env: node
    plan: starter
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: staging
      - key: DATABASE_URL
        fromDatabase:
          name: spend-smart-db-staging
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://spend-smart-frontend-staging.onrender.com
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: /api
      - key: MOCK_EXTERNAL_APIS
        value: true
    autoDeploy: true
    branch: develop
    rootDir: apps/backend

  # Production Frontend
  - type: static
    name: spend-smart-frontend-prod
    env: static
    plan: starter
    region: oregon
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://spend-smart-backend-prod.onrender.com/api
      - key: VITE_APP_NAME
        value: SpendSmart
      - key: VITE_ENABLE_ANALYTICS
        value: true
    autoDeploy: true
    branch: main
    rootDir: apps/frontend

  # Staging Frontend
  - type: static
    name: spend-smart-frontend-staging
    env: static
    plan: starter
    region: oregon
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://spend-smart-backend-staging.onrender.com/api
      - key: VITE_APP_NAME
        value: SpendSmart (Staging)
      - key: VITE_ENABLE_ANALYTICS
        value: false
    autoDeploy: true
    branch: develop
    rootDir: apps/frontend
