name: Feature Request
description: Suggest a new feature or enhancement for SpendSmart
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point does it address?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail.
      placeholder: |
        Describe how you envision this feature working:
        - What would the user interface look like?
        - How would users interact with it?
        - What would be the expected behavior?
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        Example use cases:
        1. As a user, I want to...
        2. When I..., I expect...
        3. This would help me...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - Authentication/User Management
        - Account Integration
        - Transaction Management
        - Categorization
        - Budgeting
        - Forecasting/Simulation
        - Dashboard/Reporting
        - Notifications
        - Currency Support
        - Collaboration
        - Financial Goals
        - Mobile App
        - API
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have technical implementation ideas, please share them.
      placeholder: |
        Technical implementation thoughts:
        - Database changes needed
        - API endpoints required
        - UI components needed
        - Third-party services involved
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If you have mockups, wireframes, or visual examples, please attach them.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request.
      placeholder: Any additional information, links, or references...
    validations:
      required: false

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with SpendSmart's goals
          required: true
        - label: I would be willing to help test this feature
          required: false
        - label: I would be interested in contributing to this feature
          required: false
