name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: spendsmarttest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=packages/shared

      - name: Type check
        run: |
          npm run type-check --workspace=apps/backend
          npm run type-check --workspace=apps/frontend

      - name: Lint
        run: |
          npm run lint --workspace=apps/backend
          npm run lint --workspace=apps/frontend

      - name: Test backend
        run: npm run test --workspace=apps/backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/spendsmarttest
          JWT_SECRET: test-secret
          NODE_ENV: test

      - name: Test frontend
        run: npm run test --workspace=apps/frontend

      - name: Build backend
        run: npm run build --workspace=apps/backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/spendsmarttest
          JWT_SECRET: test-secret

      - name: Build frontend
        run: npm run build --workspace=apps/frontend
        env:
          VITE_API_BASE_URL: http://localhost:3001/api
          VITE_APP_NAME: SpendSmart

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=high
